# Generated by Django 4.1 on 2022-08-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_listing_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='like_new',
            field=models.BooleanField(default=False),
        ),
    ]
