# Generated by Django 4.1 on 2022-08-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_listing_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='like_new',
        ),
    ]
