# Generated by Django 4.1 on 2022-08-21 22:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_remove_listing_like_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='photo',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/pictures'), upload_to=''),
        ),
    ]
