# Generated by Django 4.1 on 2022-08-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_rename_photo_band_photo1_band_photo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='photo2',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
