# Generated by Django 4.1 on 2022-08-21 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_alter_band_photo2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='photo1',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='band',
            name='photo2',
        ),
    ]
