# Generated by Django 4.1 on 2022-08-22 15:27

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_rename_photo1_band_photo_remove_band_photo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/pictures'), upload_to=''),
        ),
    ]
