# Generated by Django 4.1 on 2022-08-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_alter_band_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
