# Generated by Django 4.1 on 2022-08-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0013_alter_band_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/pictures/'),
        ),
    ]
