# Generated by Django 4.1 on 2022-08-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_alter_band_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='photo',
        ),
        migrations.AddField(
            model_name='band',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
