# Generated by Django 4.1 on 2022-08-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_remove_band_photo_band_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='picture',
        ),
        migrations.AddField(
            model_name='band',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
